### ISSUE TITLE
ERROR: File google-services.json is missing

### ISSUE THREAD

**Issue by zakblacki** [thanksmister/Local-Trader-Android#4]
The Google Services Plugin cannot function without it

Workaround just have to commente this line :

> //apply plugin: 'com.google.gms.google-services'

Consider adding your json file comit

Downside : app won't work crash

**Comment by thanksmister** [comment]
That file is for your Firebase instance, but it's not a file that can be shared.  What you need to do is remove the dependency for firebase in the .gradle file then remove the code in the Splash activity which checks Firebase remote config settings.   You don't need any of those to run the project, it is for crash reporting and turning on/off features remotely.

**Comment by thanksmister** [comment]
I will try to strip those out of the next commit, but they are needed for me to generate the APK file and distribute to Google Play.   If you are just compiling locally, you do not need to use Firebase.
